version: '3.8'

services:
  app:
    build: .
    container_name: them-forest-vuexy
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    networks:
      - shared-network
    ports:
      - 3001:3000

networks:
  shared-network:
    external: true
